import type { Oferta } from './types'

export const MOCK_OFERTAS: Oferta[] = [
  {
    id: '1',
    titulo: 'iPhone 15 128GB Preto',
    categoria: 'iPhone',
    preco: 3899.0,
    preco_original: 5699.0,
    desconto_pct: 32,
    vendedor: 'Apple_Store_Oficial',
    vendidos: 1243,
    link: 'https://mercadolivre.com.br',
  },
  {
    id: '2',
    titulo: 'MacBook Air M2 8GB 256GB Meia-noite',
    categoria: 'MacBook',
    preco: 8499.0,
    preco_original: null,
    desconto_pct: null,
    vendedor: 'TechStore_BR',
    vendidos: 87,
    link: 'https://mercadolivre.com.br',
  },
  {
    id: '3',
    titulo: 'AirPods Pro 2ª Geração com Estojo MagSafe',
    categoria: 'AirPods',
    preco: 1499.0,
    preco_original: 2199.0,
    desconto_pct: 32,
    vendedor: 'iPlace_Oficial',
    vendidos: 3812,
    link: 'https://mercadolivre.com.br',
  },
  {
    id: '4',
    titulo: 'iPad 10ª Geração 64GB Wi-Fi Amarelo',
    categoria: 'iPad',
    preco: 2799.0,
    preco_original: 3299.0,
    desconto_pct: 15,
    vendedor: 'Fast_Shop_Oficial',
    vendidos: 542,
    link: 'https://mercadolivre.com.br',
  },
  {
    id: '5',
    titulo: 'Apple Watch Series 9 41mm GPS Meia-noite',
    categoria: 'Apple Watch',
    preco: 2999.0,
    preco_original: 3799.0,
    desconto_pct: 21,
    vendedor: 'Apple_Store_Oficial',
    vendidos: 678,
    link: 'https://mercadolivre.com.br',
  },
  {
    id: '6',
    titulo: 'iMac M3 24" 8GB 256GB Azul',
    categoria: 'iMac',
    preco: 14999.0,
    preco_original: null,
    desconto_pct: null,
    vendedor: 'TechStore_BR',
    vendidos: 34,
    link: 'https://mercadolivre.com.br',
  },
  {
    id: '7',
    titulo: 'Mac Mini M2 8GB 256GB',
    categoria: 'Mac Mini',
    preco: 5499.0,
    preco_original: 6499.0,
    desconto_pct: 15,
    vendedor: 'Magazine_Luiza_Oficial',
    vendidos: 291,
    link: 'https://mercadolivre.com.br',
  },
  {
    id: '8',
    titulo: 'iPhone 15 Pro 256GB Titânio Natural',
    categoria: 'iPhone',
    preco: 7299.0,
    preco_original: 8999.0,
    desconto_pct: 19,
    vendedor: 'iPlace_Oficial',
    vendidos: 956,
    link: 'https://mercadolivre.com.br',
  },
  {
    id: '9',
    titulo: 'MacBook Pro M3 14" 16GB 512GB Preto Espacial',
    categoria: 'MacBook',
    preco: 16999.0,
    preco_original: 19999.0,
    desconto_pct: 15,
    vendedor: 'Fast_Shop_Oficial',
    vendidos: 112,
    link: 'https://mercadolivre.com.br',
  },
  {
    id: '10',
    titulo: 'AirPods 3ª Geração',
    categoria: 'AirPods',
    preco: 899.0,
    preco_original: null,
    desconto_pct: null,
    vendedor: 'TechStore_BR',
    vendidos: 2104,
    link: 'https://mercadolivre.com.br',
  },
  {
    id: '11',
    titulo: 'iPad Pro M4 11" 256GB Wi-Fi',
    categoria: 'iPad',
    preco: 8999.0,
    preco_original: 10499.0,
    desconto_pct: 14,
    vendedor: 'Apple_Store_Oficial',
    vendidos: 189,
    link: 'https://mercadolivre.com.br',
  },
  {
    id: '12',
    titulo: 'Apple Watch Ultra 2 49mm Titanium',
    categoria: 'Apple Watch',
    preco: 7499.0,
    preco_original: 8999.0,
    desconto_pct: 17,
    vendedor: 'Apple_Store_Oficial',
    vendidos: 76,
    link: 'https://mercadolivre.com.br',
  },
]
